[package]
name = "fix_links"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5", default-features=false,features = ["derive", "std"] }
glob = "0.3.2"
regex = "1.11.1"
urlencoding = "2.1.3"
