[package]
name = "move_command"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
clap = { version = "4.5.20", default-features = false, features = ["derive", "std"] }
regex = "1.11.1"
anyhow = "1.0.93"
