name: Build
on: [push]

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build
      - uses: actions/upload-artifact@v4
        with:
          path: |
            target/release/*
            !target/release/.fingerprint
            !target/release/build
            !target/release/deps
            !target/release/examples
            !target/release/incremental
            !target/release/.cargo-lock
            !target/release/*.d
            !target/release/*.pdb
